updated package.json and bower.json to newest versions
but have an error while setting up a new dev box.

Running "less:server" (less) task
    >> FileError: '/node_modules/bootstrap/less/bootstrap.less' wasn't found. Tried - /node_modules/bootstrap/less/bootstrap.less,client/bower_components/node_modules/bootstrap/less/bootstrap.less,client/app/node_modules/bootstrap/less/bootstrap.less,client/components/node_modules/bootstrap/less/bootstrap.less in client/app/app.less on line 6, column 1:
    >> 5
    >> 6 @import '/node_modules/bootstrap/less/bootstrap.less';
    >> 7 @import '/node_modules/font-awesome/less/font-awesome.less';
    Warning: Error compiling client/app/app.less Use --force to continue.

    Aborted due to warnings.